config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :articles do
    resources :bookmarks, only: [:create, :destroy], shallow: true
    resources :comments, only: [:create]
    member do
      post "like"
      delete :delete_image_attachment
    end
  end

  get "signup", to: "users#new"
  resources :users, except: :new do
    resources :bookmarks, only: [:index], shallow: true
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

  mount ActionCable.server => "/cable"

  get "/chat", to: "chatrooms#show"
  resources :messages, only: :create

  get "search", to: "articles#search"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :require_user
  before_action :validate_user, only: :index
  before_action :article_check, only: :create

  def index
    user = User.find(params[:user_id])
    @articles = Article.joins(:bookmarks).where("bookmarks.user_id=?", current_user.id).includes(:likes, :comments) 
    render "bookmarks/index", locals: {articles: @articles} 
  end

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    if @bookmark.save
      @article = @bookmark.article
      @is_bookmarked = @bookmark
      respond_to :js
    else
      flash[:danger] = "Something went wrong ..."
      redirect_to articles_path
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @article = @bookmark.article
    if @bookmark.destroy
      respond_to :js
    else
      flash[:danger] = "Something went wrong ..."
      redirect_to articles_path
    end
  end

  private
  def bookmark_params
    params.permit :user_id, :article_id
  end

  def validate_user
    unless params[:user_id].to_i == current_user.id
      flash[:danger] = "Invalid user"
      redirect_to user_bookmarks_path(current_user.id)
    end
  end

  def article_check
    article_id = params[:article_id]
    if !Article.find_by(id:article_id).present?
      flash[:danger] = "Articles not found"
      redirect_to articles_path
    end
  end
end

app/views/bookmarks/_bookmark.html.erb
<% if obj.size == 0 %>
  <h3 class="text-center"> No Bookmarks </h3>
  <% end %> 
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info text-center">
        <%= image_tag(article.user.display_image1, class: "custom-image-style") if article.user.image.attached? %>
      </section>
    </div>
    <div class="col-md-10 well">
      <div class="pull-right">
       <%= image_tag(article.image.attachments.first, size: "160x130") if article.image.attached? %>
      </div>
      <h4><%= link_to article.name, article_path(id: article.id) %></h4>
      <p><%= truncate(article.description, length: 250) %></p>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <p>
        <span class="quiet">Created: <small><%= time_ago_in_words(article.created_at) %>
        ago by <%= article.user.username %> | <%= pluralize(article.comments.count, "Comment") %></small></span>
      </p>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="articles-actions">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-warning btn-fix" %>
          <%= link_to "Delete this article", article_path(article),
                      method: :delete,
                      data: { confirm: "Are you sure that you want to delete this article?" },
                      class: "btn btn-xs btn-danger btn-fix" %>
        </div>
      <% end %>
      </br>
      <div class="row">
      <div class="pull-right liking">
        <span id="thumbs-up-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: true} %>
        </span>
        <span id="thumbs-down-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: false} %>
        </span>
      </div>

       <div id="bookmark-icon-post-<%= article.id.to_s %>" class="ml-auto">
          <%= render "articles/bookmark_icon", { is_bookmarked: article.is_bookmarked(current_user), article: article } %>
        </div>



      </div>
    </div>
  </div>
  
<% end %>

app/views/bookmarks/create.js.erb
$('#bookmark-icon-post-<%= @article.id.to_s %>').
  html('<%= j render "articles/bookmark_icon", {is_bookmarked: @is_bookmarked, article: @article} %>');
console.log("create bookmark success");

app/views/bookmarks/destroy.js.erb
$('#bookmark-icon-post-<%= @article.id.to_s %>').
  html('<%= j render "articles/bookmark_icon", {is_bookmarked: @is_bookmarked, article: @article} %>');
console.log("delete bookmark success");

app/views/bookmarks/index.html.erb
<%= render 'shared/page_title', title: "Bookmarks " %>

<div class="text-center">
  
</div>

<%= render 'bookmark', obj: articles %>
<div class="text-center">
  
</div>