config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :articles do
    resources :bookmarks, only: [:create, :destroy], shallow: true
    resources :comments, only: [:create]
    member do
      post "like"
      delete :delete_image_attachment
    end
  end

  get "signup", to: "users#new"
  resources :users, except: :new do
    resources :bookmarks, only: [:index], shallow: true
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

  mount ActionCable.server => "/cable"

  get "/chat", to: "chatrooms#show"
  resources :messages, only: :create

  get "search", to: "articles#search"
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :name_format, :description_format

  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many_attached :image

  default_scope -> { order(updated_at: :desc) }

  validates :name, :description, :user_id, presence: true
  validates :description, length: { minimum: 5, maximum: 10000 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size: { less_than: 5.megabytes,
                            message: "should be less than 5MB" }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  def is_bookmarked user
    Bookmark.find_by(user_id: user.id, article_id: id)
  end


  def display_image(image)
    image.variant(combine_options: {
      auto_orient: true,
      gravity: "center",
      resize: "250x250^",
      crop: "250x250+0+0",
    })
  end

  private

  def name_format
    self.name = name.split.map(&:capitalize) * " "
  end

  def description_format
    self.description = description.capitalize
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def search
    @articles = Article.where("name Like ?", "%" + params[:q].to_s + "%")
  end

  def new
    @article = Article.new
  end

  def create
    
    @article = Article.new(article_params)
    # @article.image.attach(params[:article][:image]) if params[:article][:image].present?
    @article.user = current_user
        
    if @article.save
      flash[:success] = "Article was created successfully!"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.paginate(page: params[:page], per_page: 5)
    @is_bookmarked = @article.is_bookmarked(current_user)
  end

  def edit
  end

  def update
    @article.image.attachments.purge
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully!"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    if @article.present?
        @article.destroy
        flash[:success] = "Article deleted successfully!" 
    else
        flash[:danger] = "You cannot perform this action"
    
    end
    redirect_to articles_path
  end

  def like
    like = @article.likes.where(user_id: current_user.id).first
    if like.present?
      like.update!(like: params[:like])
    else
      like = Like.create(like: params[:like], user: current_user, article: @article)
    end
    #redirect_to request.referrer
  end

  def delete_image_attachment
    @article = Article.find(params[:id])
    @article.image.attachments.purge
  end

  private

  def set_article
    @article = Article.find_by(id:params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :description, image: [], category_ids: [])
  end

  def require_same_user
    if @article.blank?
      flash[:danger] = "Articles not found"
      redirect_to articles_path
    elsif current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to articles_path
    end
  end

  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info text-center">
        <%= image_tag(article.user.display_image1, class: "custom-image-style") if article.user.image.attached? %>
      </section>
    </div>
    <div class="col-md-10 well">
      <div class="pull-right">
        <%= image_tag(article.image.attachments.first, size: "160x130") if article.image.attached? %>
      </div>
      <h3><%= link_to article.name, article_path(id: article.id) %></h3>
      <p><%= truncate(article.description, length: 300) %></p>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <p>
        <span class="quiet">Created: <small><%= time_ago_in_words(article.created_at) %>
            ago by <%= article.user.username %> | <%= pluralize(article.comments.count, "Comment") %></small></span>
      </p>
      <div class="articles-actions">
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-warning btn-fix" %>
          <%= link_to "Delete this article", article_path(article),
                      method: :delete,
                      data: { confirm: "Are you sure that you want to delete this article?" },
                      class: "btn btn-xs btn-danger btn-fix" %>
        <% end %>
      </div>
    </br>
    <div class="row">
      <div class="pull-right liking">
        <span id="thumbs-up-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: true} %>
        </span>
        <span id="thumbs-down-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: false} %>
        </span>
      </div>
      <div id="bookmark-icon-post-<%= article.id.to_s %>" class="ml-auto">
        <%= render "articles/bookmark_icon", { is_bookmarked: article.is_bookmarked(current_user), article: article } %>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= javascript_tag do %>
  jQuery(".article-thumbs-up, .article-thumbs-down").unbind().click(function(event) {
      jQuery.ajax({
          url: this.dataset.url,
          method: 'POST',
          success: function(result) {
          }
      })
  })
<% end %>

app/views/articles/_article1.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-10 well well2">
      <div class="pull-right">
        <%= image_tag(article.image.attachments.first, size: "160x130") if article.image.attached? %>
      </div>
      <h4><%= link_to article.name, article_path(id: article.id) %></h4>
      <p><%= truncate(article.description, length: 300) %></p>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <p>
        <span class="quiet">Created: <small><%= time_ago_in_words(article.created_at) %>
            ago by <%= article.user.username %> | <%= pluralize(article.comments.count, "Comment") %></small></span>
      </p>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="articles-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-warning btn-fix" %>
          <%= link_to "Delete this article", article_path(article),
                      method: :delete,
                      data: { confirm: "Are you sure that you want to delete this article?" },
                      class: "btn btn-xs btn-danger btn-fix" %>
        </div>
      <% end %>
    </br>
    <div class="row">
      <div class="pull-right liking">
        <span id="thumbs-up-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: true} %>
        </span>
        <span id="thumbs-down-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: false} %>
        </span>
      </div>
      <div id="bookmark-icon-post-<%= article.id.to_s %>" class="ml-auto">
        <%= render "articles/bookmark_icon", { is_bookmarked: article.is_bookmarked(current_user), article: article } %>
      </div>
    </div>
  </div>
</div>
<% end %>
<%= javascript_tag do %>
  jQuery(document).on("click", ".article-thumbs-up, .article-thumbs-down", function(event) {
  jQuery.ajax({
  url: this.dataset.url,
  method: 'POST',
  success: function(result) {
  }
  })
  })
<% end %>

app/views/articles/_article1.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-10 well well2">
      <div class="pull-right">
        <%= image_tag(article.image.attachments.first, size: "160x130") if article.image.attached? %>
      </div>
      <h3><%= link_to article.name, article_path(id: article.id) %></h3>
      <p><%= truncate(article.description, length: 300) %></p>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      <p>
        <span class="quiet">Created: <small><%= time_ago_in_words(article.created_at) %>
            ago by <%= article.user.username %> | <%= pluralize(article.comments.count, "Comment") %></small></span>
      </p>
      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="articles-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-warning btn-fix" %>
          <%= link_to "Delete this article", article_path(article),
                      method: :delete,
                      data: { confirm: "Are you sure that you want to delete this article?" },
                      class: "btn btn-xs btn-danger btn-fix" %>
        </div>
      <% end %>
    </br>
    <div class="row">
      <div class="pull-right liking">
        <span id="thumbs-up-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: true} %>
        </span>
        <span id="thumbs-down-wrapper-<%= article.id %>">
          <%= render "articles/like_icon", {article: article, like: false} %>
        </span>
      </div>
      <div id="bookmark-icon-post-<%= article.id.to_s %>" class="ml-auto">
        <%= render "articles/bookmark_icon", { is_bookmarked: article.is_bookmarked(current_user), article: article } %>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= javascript_tag do %>
  jQuery(".article-thumbs-up, .article-thumbs-down").unbind().click(function(event) {
      jQuery.ajax({
          url: this.dataset.url,
          method: 'POST',
          success: function(result) {
          }
      })
  })
<% end %>

app/views/articles/_article_home.erb
<div class="row m-x-0">
  <% obj.each do |article| %>
    <div class="col-md-5 well">
      <h4><strong style="text-transform: uppercase"><%= link_to article.name, article_path(id: article.id) %></strong></h4>
      <p><%= truncate(article.description, length: 250) %></p>
    </div>
  <% end %>
</div>

app/views/articles/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
  <%= link_to "Bookmarked", bookmark_path(is_bookmarked), method: :delete, remote: true,
    class: "core-sprite bookmarked hide-text" %>
<% else %>
  <%= link_to "Bookmark", article_bookmarks_path(article), method: :post,
    remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => { class: "form-horizontal", multipart: true, role: "form" }) do |f| %>
  <div class="form-group">
      <%= f.label :name, class: "control-label col-md-2" %>
      <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Name of article", autofocus: true %>
      </div>
  </div>
  
  <div class="form-group">
    <%= f.label :description, class: "control-label col-md-2" %>
    <div class="col-md-8">
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Write article" %>
    </div>
  </div>
  
  <div class="form-group">
  <%= f.label :image, "Select Categories", class: "control-label col-md-2" %>
    <div class="col-md-8">
    
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            {  }, { multiple: true, size: 2, class: "custom-select shadow rounded coll" }) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, "Image", class: "control-label col-md-2" %>
    <div class="col-md-8">
      <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", multiple: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-8 ">
      <% if @article.id.present? && @article.image.attached? %>
          <%= link_to "Remove Image ", delete_image_attachment_article_path(@article),
                      method: :delete,
                      data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xlg" %>
                        <% end %>
    </div>
  </div>



  <div class="form-group">
    <div class="col-md-offset-2 col-md-8 ">
      <%= f.submit class: "btn btn-primary btn-xlg" %>
    </div>
  </div>
<% end %>


<script type="text/javascript">
  $("#article_image").bind("change", function() {
    const size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#article_image").val("");
    }
  });
</script>

app/views/articles/_like_icon.html.erb
<% if article.likes.where(user_id: current_user.id).present? %>
    <% if article.likes.where(user_id: current_user.id).first.like? && like %>
        <% fa_class = "fa-solid"%>
    <% elsif !article.likes.where(user_id: current_user.id).first.like? && !like %>
        <% fa_class = "fa-solid"%>
    <% else %>
        <% fa_class = "fa-regular"%>
    <% end %>
<% else %>
    <% fa_class = "fa-regular"%>
<% end %>

<% if like %>
    <%= link_to("javascript:void(0)", class: "article-thumbs-up", data: { url: like_article_path(article, like: true) }) do%>
        <i class="<%= fa_class %> fa-thumbs-up"> </i>
    <% end %>            
    <%= article.thumbs_up_total %>
<% else %>
    <%= link_to("javascript:void(0)", class: "article-thumbs-down", data: { url: like_article_path(article, like: false) }) do%>
        <i class="<%= fa_class %> fa-thumbs-down"> </i>
    <% end %>
    <%= article.thumbs_down_total %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'shared/errors', obj: @article %>
<%= render 'shared/page_title', title: "Edit your article" %>
<%= render 'form' %>

app/views/articles/index.html.erb
<%= render "shared/page_title", title: " Articles Feed", class:"ali"%>
<p class="flash"><%= notice %></p>

<form class="navbar-form" action="/search" >
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search Articles..." name="q" required>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>


<style>
  .dropbtn {
    background-color: black;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
  }

  .dropdown {
    position: relative;
    display: inline-block;
    float:right;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  .dropdown-content li {
    color: black !important;
    padding: 12px 16px;
    text-decoration: none !important;
    display: block;
  }

  .log{
    color: black !important;
    text-decoration: none !important;
    font-weight : 550 !important ;
  }

  .log1{
    color: blue !important;
    text-decoration: none !important;
    font-weight : bold !important ;
  }

  .dropdown-content li:hover {background-color: #f1f1f1}

  .dropdown:hover .dropdown-content {
    display: block;
    float:left;
  }
</style>


<div class="text-center">
  <%= will_paginate @articles %>
  <div class="dropdown">
    <button class="dropbtn"><span style="font-size: 20px"  >Categories</span></button>
    <div class="dropdown-content">
      <li><%= link_to "All Categories", categories_path , class:"log1" %></li>
      <% Category.order(:name).each do |category| %>
        <li><%= link_to category.name, category_path(category) , class:"log" %></li>
      <% end %>
    </div>
  </div>
</div>
<%= render "article", obj: @articles %>
<div class="text-center ">
  <%= will_paginate @articles %>
</div>

app/views/articles/like.js.erb
jQuery("#thumbs-up-wrapper-<%= @article.id %>").html('<%= j render "like_icon", {article: @article, like: true} %>');
jQuery("#thumbs-down-wrapper-<%= @article.id %>").html('<%= j render "like_icon", {article: @article, like: false} %>');

 jQuery(".article-thumbs-up, .article-thumbs-down").unbind().click(function(event) {
      jQuery.ajax({
          url: this.dataset.url,
          method: 'POST',
          success: function(result) {
          }
      })
  })

app/views/articles/new.html.erb
<%= render 'shared/errors', obj: @article %>
<%= render 'shared/page_title', title: "Create a New article" %>
<%= render 'form' %>

app/views/articles/search.html.erb
<h1 class="text-center"> Searched Articles </h1>
</br>
<%= render 'article', obj: @articles %>

app/views/articles/show.html.erb
<%= render "shared/page_title", title: @article.name %>
<div align = "center">
  <% @article.image.attachments.each do |image| %>
    <%= image_tag(@article.display_image(image), class: "custom-image-style") %> &nbsp; &nbsp;
  <% end %>
</div>
<div align = "center">
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="well1 col-md-8 col-md-offset-2">
    <%= simple_format(@article.description, class: 'desc') %>
    <hr>
    <p class="text-center">
      <em>Created by:</em>
    </p>
    <p class="text-center">
      <h5><%= image_tag(@article.user.display_image2, class: "custom-image-style") if @article.user.image.attached? %></h5>
    </p>
    <p class="text-center">
      <h4><%= @article.user.username %></h4>
      <%= time_ago_in_words(@article.created_at) %> ago
    </p>
    <div class="articles-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <div class="articles-actions">
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-warning btn-fix" %>
          <%= link_to "Delete this article", article_path(@article),
                      method: :delete,
                      data: { confirm: "Are you sure that you want to delete this article?" },
                      class: "btn btn-xs btn-danger btn-fix" %>
        </div>
      <% end %>
    </center>
  </div>
</div>
</div>
</div>
<div class="row marg">
  <div class="pull-right liking1">
    <span id="thumbs-up-wrapper-<%= @article.id %>">
      <%= render "articles/like_icon", { article: @article, like: true } %>
    </span>
    <span id="thumbs-down-wrapper-<%= @article.id %>">
      <%= render "articles/like_icon", { article: @article, like: false } %>
    </span>
  </div>
</div>
<div class="col-md-2 book">
  <div id="bookmark-icon-post-<%= @article.id.to_s %>" class="ml-auto">
    <%= render "bookmark_icon", { is_bookmarked: @article.is_bookmarked(current_user), article: @article } %>
  </div>
</div>
</div>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <hr>
      <%= form_for([@article, @comment], remote: true, html: { class: "form-horizontal" }) do |f| %>
        <div class="form-group">
          <%= f.label :description, "Comment:", class: "control-label col-md-2" %>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 3, class: "form-control", placeholder: "Enter comment here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit comment", class: "btn btn-primary btn-lg btn-xlg" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>
<% if @article.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3 class="wid">Bloggers Comments: </h3>
      <div id="messages">
        <%= render partial: "comments/comments", object: @comments %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No comments yet!</h3>
    </div>
  </div>
<% end %>

<%= javascript_tag do %>
  jQuery(".article-thumbs-up, .article-thumbs-down").click(function(event) {
      jQuery.ajax({
          url: this.dataset.url,
          method: 'POST',
          success: function(result) {
          }
      })
  })
<% end %>