config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :articles do
    resources :bookmarks, only: [:create, :destroy], shallow: true
    resources :comments, only: [:create]
    member do
      post "like"
      delete :delete_image_attachment
    end
  end

  get "signup", to: "users#new"
  resources :users, except: :new do
    resources :bookmarks, only: [:index], shallow: true
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

  mount ActionCable.server => "/cable"

  get "/chat", to: "chatrooms#show"
  resources :messages, only: :create

  get "search", to: "articles#search"
end

app/models/category.rb
class Category < ApplicationRecord
  #before_save :name_capitalize
  validates :name, presence: true, length: { minimum: 3, maximum: 25 },uniqueness: true, uniqueness: { case_sensitive: false }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories


  private
  def name_capitalize
    self.name = name.capitalize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user
  before_action :require_admin, except: [:show, :index]
  
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:danger] = "Selected Category have been deleted"
      redirect_to @category
    else
      flash[:danger] = "ERROR"
    end
  end
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/views/categories/_category.html.erb
<span class="badge badge-light"><%= link_to category.name, category_path(category) %> </span>&nbsp;

app/views/categories/_form.html.erb
<%= form_for @category, html: {class:'form-horizontal'} do |f| %>
  <div class="form-group">
      <%= f.label :name, class:"control-label col-md-2" %>
      <div class="col-md-8">
        <%= f.text_field :name, class:'form-control', placeholder: "Enter category", autofocus: true %>
      </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-8">
      <%= f.submit(@category.new_record? ? "Add category" : "Update category",
      class:'btn btn-primary btn-lg btn-xlg') %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "shared/errors", obj: @category %>
<%= render 'shared/page_title', title: "Edit #{@category.name}" %>
<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/page_title', title: "Available categories" %>
<% if @categories.size == 0 %>
  <h3 class="text-center"> No Categories Available</h3>
<% end %> 
<div class="text-center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="user-title"><%= link_to category.name.capitalize, category_path(category) %></li>
          <li><small><%= pluralize(category.articles.count, 'article')  if category.articles %></small></li>
          <% if logged_in? && current_user.admin? %>
            <li>
              <%= link_to "Edit this category", edit_category_path(category) %>
            </li>
            <li>
              <%= link_to "Delete this category", category_path(category), method: :delete,
              data: { confirm:
              "Are you sure you want to delete the user and all associated articles?"} %>
            </li>
            <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<%= render "shared/errors", obj: @category %>
<%= render 'shared/page_title', title: "Enter a New category" %>
<%= render 'form' %>

app/views/categories/show.html.erb
<%= render 'shared/page_title', title: "#{@category.name}" %>

<% if @category.articles.count != 0 %>
  <div class="text-center">
    <%= will_paginate @category_articles %>
  </div>
  <%= render 'articles/article', obj: @category_articles %>
  <div class="text-center">
    <%= will_paginate @category_articles %>
  </div>
<% else %>
  <h4 class="text-center">No articles yet!</h4>
<% end %>

<%= javascript_tag do %>
  jQuery(document).on("click", ".article-thumbs-up, .article-thumbs-down", function(event) {
  // showpage
  jQuery.ajax({
  url: this.dataset.url,
  method: 'POST',
  success: function(result) {
  }
  })
  })
<% end %>