config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :articles do
    resources :bookmarks, only: [:create, :destroy], shallow: true
    resources :comments, only: [:create]
    member do
      post "like"
      delete :delete_image_attachment
    end
  end

  get "signup", to: "users#new"
  resources :users, except: :new do
    resources :bookmarks, only: [:index], shallow: true
  end

  get "/login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

  mount ActionCable.server => "/cable"

  get "/chat", to: "chatrooms#show"
  resources :messages, only: :create

  get "search", to: "articles#search"
end

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <strong><a href="#"></a>A Demo Application</strong>
    by <em><a href="#">Mithun Raam</a></em>
  </small>
  <nav>
    <ul>
      <a href="https://www.linkedin.com/in/mithun-raam/" target = "blank" >About Me</a>
    </ul>
  </nav>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TechCrunch", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" >
        <% if logged_in? %>
          <li><%= link_to "Articles Feed", articles_path, id: "logo1" %></li>
          <li><%= link_to "Bloggers", users_path, id: "logo1" %></li>
          <li><%= link_to "Chat", chat_path, id: "logo1" %></li>
          <li><%= link_to "Create Article", new_article_path, id: "logo1" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false" id="logo1" >Categories 
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if logged_in? && current_user.admin? %>
                <li><%= link_to "New category", new_category_path %></li>
              <% end%>
              <li><%= link_to "All Categories", categories_path %></li>
            </ul>
          </li>
          <li><%= link_to "Bookmarks", user_bookmarks_path(current_user.id), id: "logo1" %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="logo2"
            role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %><%= "(Admin)" if current_user.admin? %></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li class="siz" ><%= link_to "Log in", login_path, id: "logo1" %></li>
      <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>My Blog App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/flash_messages" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>